#!/bin/bash
#
# Helper script to gracefully power-down unRAID server.
PROG_NAME="Powerdown"
SECONDS=0
TIMEOUT=10

if [ "${1}" == "-r" ]; then
	OPT="reboot"
	logger "Rebooting server..." -t"${PROG_NAME}"
else
	OPT="shutdown"
	logger "Shuting down server..." -t"${PROG_NAME}"
fi

port=$(lsof -i -P -sTCP:LISTEN|grep -Pom1 '^emhttp.*:\K\d+')

# Access a blank page in case this is first request since startup.
/usr/bin/wget -q -O - localhost:$port/update.htm >/dev/null

# Have emhttp do all the work as if user clicked 'shutdown or reboot' in webGui.
/usr/bin/wget -q --timeout=${TIMEOUT} -O - localhost:$port/update.htm?${OPT}=apply >/dev/null

if ((${SECONDS} >= ${TIMEOUT})); then
	logger "emhttp timed out - doing a hard poweroff..." -t"${PROG_NAME}"
	# Take it down hard
	/sbin/poweroff
fi
